export const COMPONENTS = [
  {
    id: 'card',
    name: 'Cards',
    emoji: '🃏',
    desc: 'Floating glass cards with depth and blur effects. Perfect for content containers.',
    badge: 'Popular',
    color: 'accent',
    tags: ['layout', 'container'],
  },
  {
    id: 'button',
    name: 'Buttons',
    emoji: '🔘',
    desc: 'Interactive frosted CTAs with shimmer effects and hover states.',
    badge: 'Essential',
    color: 'green',
    tags: ['interactive', 'cta'],
  },
  {
    id: 'modal',
    name: 'Modals',
    emoji: '🔲',
    desc: 'Backdrop-blur dialog overlays for focus interactions and alerts.',
    badge: 'UI',
    color: 'blue',
    tags: ['overlay', 'dialog'],
  },
  {
    id: 'tooltip',
    name: 'Tooltips',
    emoji: '📌',
    desc: 'Frosted glass contextual hints that appear on hover or focus.',
    badge: 'UI',
    color: 'purple',
    tags: ['overlay', 'hint'],
  },
  {
    id: 'toast',
    name: 'Toasts',
    emoji: '🔔',
    desc: 'Non-intrusive glass notification banners for feedback.',
    badge: 'Feedback',
    color: 'accent',
    tags: ['notification', 'feedback'],
  },
  {
    id: 'dropdown',
    name: 'Dropdowns',
    emoji: '⬆️',
    desc: 'Blurred floating selection menus with smooth open/close transitions.',
    badge: 'UI',
    color: 'green',
    tags: ['input', 'select'],
  },
  {
    id: 'badge',
    name: 'Badges',
    emoji: '🏷️',
    desc: 'Tinted translucent label chips for status and categorization.',
    badge: 'Label',
    color: 'blue',
    tags: ['label', 'status'],
  },
  {
    id: 'chart',
    name: 'Charts',
    emoji: '📊',
    desc: 'Data visualization wrapped in glass container layers.',
    badge: 'Data',
    color: 'purple',
    tags: ['data', 'analytics'],
  },
  {
    id: 'form',
    name: 'Forms',
    emoji: '📋',
    desc: 'Input fields and form elements with glassmorphism styling.',
    badge: 'Input',
    color: 'accent',
    tags: ['input', 'form'],
  },
  {
    id: 'table',
    name: 'Tables',
    emoji: '🔢',
    desc: 'Striped glass rows with frosted header and sort controls.',
    badge: 'Data',
    color: 'green',
    tags: ['data', 'list'],
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    emoji: '📐',
    desc: 'Fixed-position frosted navigation pane with icon and label support.',
    badge: 'Layout',
    color: 'blue',
    tags: ['navigation', 'layout'],
  },
  {
    id: 'tabs',
    name: 'Tabs',
    emoji: '🎛️',
    desc: 'Glass panel switcher with animated active indicator.',
    badge: 'Navigation',
    color: 'purple',
    tags: ['navigation', 'layout'],
  },
  {
    id: 'navbar',
    name: 'Navbar',
    emoji: '🌐',
    desc: 'Sticky top navigation bar with glass blur on scroll.',
    badge: 'Layout',
    color: 'accent',
    tags: ['navigation', 'layout'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    emoji: '👤',
    desc: 'User avatar with glass ring, status indicator and stacked groups.',
    badge: 'UI',
    color: 'green',
    tags: ['media', 'user'],
  },
  {
    id: 'progress',
    name: 'Progress',
    emoji: '📈',
    desc: 'Animated glass progress bars and circular indicators.',
    badge: 'Feedback',
    color: 'blue',
    tags: ['feedback', 'status'],
  },
  {
    id: 'slider',
    name: 'Slider',
    emoji: '🎚️',
    desc: 'Glass-styled range sliders with custom thumb and track.',
    badge: 'Input',
    color: 'purple',
    tags: ['input', 'control'],
  },
];

export const COLOR_MAP = {
  accent: { text: 'text-[#e4ff3c]', border: 'border-[rgba(228,255,60,0.2)]', bg: 'bg-[rgba(228,255,60,0.06)]' },
  green:  { text: 'text-[#3cffa0]', border: 'border-[rgba(60,255,160,0.2)]', bg: 'bg-[rgba(60,255,160,0.06)]' },
  blue:   { text: 'text-[#3c9fff]', border: 'border-[rgba(60,159,255,0.2)]', bg: 'bg-[rgba(60,159,255,0.06)]' },
  purple: { text: 'text-[#c43cff]', border: 'border-[rgba(196,60,255,0.2)]', bg: 'bg-[rgba(196,60,255,0.06)]' },
};
